"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

const SunIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="5" />
        <line x1="12" y1="1" x2="12" y2="3" />
        <line x1="12" y1="21" x2="12" y2="23" />
        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
        <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
        <line x1="1" y1="12" x2="3" y2="12" />
        <line x1="21" y1="12" x2="23" y2="12" />
        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
        <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
    </svg>
);

const MoonIcon = () => (
    <svg viewBox="0 0 24 24" fill="currentColor">
        <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z" />
    </svg>
);

const ArrowIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M5 12h14M12 5l7 7-7 7" />
    </svg>
);

// Tool Icon Components
const AIDetectorIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="11" cy="11" r="8" />
        <path d="m21 21-4.35-4.35" />
        <path d="M11 8v6M8 11h6" />
    </svg>
);

const CitationIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
        <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
        <path d="M8 7h8M8 11h8M8 15h4" />
    </svg>
);

const GrammarIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z" />
        <path d="m9 12 2 2 4-4" />
    </svg>
);

const ParaphraserIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
        <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
    </svg>
);

const SummarizerIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
        <polyline points="14 2 14 8 20 8" />
        <line x1="16" y1="13" x2="8" y2="13" />
        <line x1="16" y1="17" x2="8" y2="17" />
        <polyline points="10 9 9 9 8 9" />
    </svg>
);

const TranslatorIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <line x1="2" y1="12" x2="22" y2="12" />
        <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
);

const toolIcons: Record<string, React.FC> = {
    "ai-detector": AIDetectorIcon,
    "citation-creator": CitationIcon,
    "grammar-checker": GrammarIcon,
    "paraphraser": ParaphraserIcon,
    "summarizer": SummarizerIcon,
    "translator": TranslatorIcon,
};

// Tool data (alphabetical order)
const toolsData: Record<string, {
    name: string;
    description: string;
    longDescription: string;
    placeholder: string;
    buttonText: string;
    features: string[];
}> = {
    "ai-detector": {
        name: "AI Detector",
        description: "Instantly identify AI-generated content with precision.",
        longDescription: "Our advanced AI detection algorithm analyzes text patterns, writing styles, and linguistic markers to determine whether content was written by a human or generated by AI. Perfect for educators, publishers, and content managers who need to verify content authenticity.",
        placeholder: "Paste your text here to detect if it was written by AI...",
        buttonText: "Analyze Text",
        features: ["99.9% accuracy rate", "Detects GPT-4, Claude, and more", "Detailed confidence scores", "Highlight AI-written sections"]
    },
    "citation-creator": {
        name: "Citation Creator",
        description: "Generate accurate citations in any format instantly.",
        longDescription: "Create perfectly formatted citations in MLA, APA, Chicago, Harvard, and 50+ other styles. Simply paste a URL, ISBN, DOI, or enter details manually, and our tool will generate accurate citations ready to use in your academic work.",
        placeholder: "Paste a URL, ISBN, or DOI to generate a citation...",
        buttonText: "Generate Citation",
        features: ["50+ citation styles", "Auto-detect from URLs", "Export to Word & Google Docs", "Bibliography management"]
    },
    "grammar-checker": {
        name: "Grammar Checker",
        description: "Eliminate errors and polish your prose to perfection.",
        longDescription: "Our AI-powered grammar checker goes beyond basic spell check. It analyzes context, catches complex grammatical errors, suggests style improvements, and helps you write with clarity and confidence. Perfect for professionals and students alike.",
        placeholder: "Start typing or paste your text to check grammar...",
        buttonText: "Check Grammar",
        features: ["Context-aware corrections", "Style suggestions", "Tone analysis", "Plagiarism detection"]
    },
    "paraphraser": {
        name: "Paraphraser",
        description: "Rewrite content with clarity, style, and originality.",
        longDescription: "Transform any text while preserving its original meaning. Our paraphraser offers multiple rewriting modes — from simple rephrasing to complete style transformations. Perfect for avoiding plagiarism, improving readability, or adapting content for different audiences.",
        placeholder: "Paste the text you want to paraphrase...",
        buttonText: "Paraphrase",
        features: ["Multiple rewriting modes", "Preserve original meaning", "Adjustable creativity level", "Fluency optimization"]
    },
    "summarizer": {
        name: "Summarizer",
        description: "Condense lengthy content into key insights instantly.",
        longDescription: "Extract the most important information from any document, article, or text. Our AI summarizer understands context and identifies key points, saving you hours of reading while ensuring you don't miss critical information.",
        placeholder: "Paste the text you want to summarize...",
        buttonText: "Summarize",
        features: ["Adjustable summary length", "Bullet point mode", "Key points extraction", "PDF & URL support"]
    },
    "translator": {
        name: "Translator",
        description: "Break language barriers with nuanced, context-aware translations.",
        longDescription: "Translate text between 100+ languages with remarkable accuracy and natural fluency. Our translator understands idioms, cultural context, and technical terminology to deliver translations that read like they were written by a native speaker.",
        placeholder: "Enter text to translate...",
        buttonText: "Translate",
        features: ["100+ languages", "Context-aware translation", "Technical terminology support", "Document translation"]
    }
};

export default function ToolPage() {
    const params = useParams();
    const slug = params.slug as string;
    const tool = toolsData[slug];

    const [theme, setTheme] = useState<"light" | "dark">("light");
    const [isScrolled, setIsScrolled] = useState(false);
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [inputText, setInputText] = useState("");
    const [outputText, setOutputText] = useState("");
    const [isProcessing, setIsProcessing] = useState(false);

    useEffect(() => {
        const savedTheme = localStorage.getItem("theme");
        const systemPrefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

        if (savedTheme === "dark" || (!savedTheme && systemPrefersDark)) {
            setTheme("dark");
            document.documentElement.setAttribute("data-theme", "dark");
        }

        const handleScroll = () => setIsScrolled(window.scrollY > 50);
        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    const toggleTheme = () => {
        const newTheme = theme === "light" ? "dark" : "light";
        setTheme(newTheme);
        document.documentElement.setAttribute("data-theme", newTheme);
        localStorage.setItem("theme", newTheme);
    };

    const handleProcess = () => {
        if (!inputText.trim()) return;

        setIsProcessing(true);
        // Simulate processing
        setTimeout(() => {
            setOutputText(`This is a demo output for the ${tool?.name || 'tool'}. In a production environment, this would show the actual AI-processed result of your input text.`);
            setIsProcessing(false);
        }, 1500);
    };

    if (!tool) {
        return (
            <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: "20px" }}>
                <h1>Tool Not Found</h1>
                <Link href="/" className="btn btn-primary">Return Home</Link>
            </div>
        );
    }

    return (
        <div className="page-transition">
            {/* Navigation */}
            <nav className={`navbar ${isScrolled ? "scrolled" : ""}`}>
                <div className="container">
                    <div className="navbar-inner">
                        <Link href="/" className="logo">
                            Kreative<span>Space</span>
                        </Link>

                        <ul className="nav-links">
                            <li><Link href="/#tools">Tools</Link></li>
                            <li><Link href="/#features">Features</Link></li>
                            <li><Link href="/#how-it-works">How It Works</Link></li>
                            <li><Link href="/pricing">Pricing</Link></li>
                        </ul>

                        <div className="nav-actions">
                            <button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme">
                                {theme === "light" ? <MoonIcon /> : <SunIcon />}
                            </button>
                            <Link href="/login" className="btn btn-secondary">
                                Log In
                            </Link>
                            <Link href="/pricing" className="btn btn-primary">
                                Get Started Free
                            </Link>
                            <button
                                className="mobile-menu-btn"
                                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                                aria-label="Toggle menu"
                            >
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
            </nav>

            {/* Mobile Menu */}
            <div className={`mobile-menu ${mobileMenuOpen ? "active" : ""}`}>
                <ul className="mobile-menu-links">
                    <li><Link href="/#tools" onClick={() => setMobileMenuOpen(false)}>Tools</Link></li>
                    <li><Link href="/#features" onClick={() => setMobileMenuOpen(false)}>Features</Link></li>
                    <li><Link href="/#how-it-works" onClick={() => setMobileMenuOpen(false)}>How It Works</Link></li>
                    <li><Link href="/pricing" onClick={() => setMobileMenuOpen(false)}>Pricing</Link></li>
                    <li><Link href="/login" onClick={() => setMobileMenuOpen(false)}>Log In</Link></li>
                </ul>
            </div>

            {/* Tool Hero */}
            <section className="tool-page-hero">
                <div className="container">
                    <div className="hero-content">
                        <div className="tool-icon">{toolIcons[slug] && React.createElement(toolIcons[slug])}</div>
                        <h1>{tool.name}</h1>
                        <p style={{ fontSize: "20px", maxWidth: "700px", margin: "0 auto" }}>
                            {tool.longDescription}
                        </p>
                    </div>
                </div>
            </section>

            {/* Tool Workspace */}
            <section className="tool-workspace">
                <div className="container">
                    <div className="workspace-container">
                        <div className="workspace-header">
                            <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                                <div className="tool-icon">{toolIcons[slug] && React.createElement(toolIcons[slug])}</div>
                                <span style={{ fontWeight: 600 }}>{tool.name}</span>
                            </div>
                            <div style={{ marginLeft: "auto", display: "flex", gap: "8px" }}>
                                {tool.features.slice(0, 2).map((feature, i) => (
                                    <span
                                        key={i}
                                        style={{
                                            padding: "6px 12px",
                                            background: "var(--bg-secondary)",
                                            borderRadius: "50px",
                                            fontSize: "13px",
                                            color: "var(--text-secondary)"
                                        }}
                                    >
                                        {feature}
                                    </span>
                                ))}
                            </div>
                        </div>

                        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", minHeight: "400px" }}>
                            {/* Input */}
                            <div style={{ borderRight: "1px solid var(--card-border)" }}>
                                <div style={{ padding: "16px 32px", borderBottom: "1px solid var(--card-border)", fontSize: "14px", fontWeight: 600, color: "var(--text-muted)" }}>
                                    INPUT
                                </div>
                                <textarea
                                    className="workspace-textarea"
                                    placeholder={tool.placeholder}
                                    value={inputText}
                                    onChange={(e) => setInputText(e.target.value)}
                                    style={{ minHeight: "350px" }}
                                />
                            </div>

                            {/* Output */}
                            <div>
                                <div style={{ padding: "16px 32px", borderBottom: "1px solid var(--card-border)", fontSize: "14px", fontWeight: 600, color: "var(--text-muted)" }}>
                                    OUTPUT
                                </div>
                                <div style={{ padding: "32px", minHeight: "350px", color: outputText ? "var(--text-primary)" : "var(--text-muted)", fontFamily: "var(--font-body)", fontSize: "16px", lineHeight: 1.8 }}>
                                    {isProcessing ? (
                                        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                                            <div className="spinner" style={{
                                                width: "20px",
                                                height: "20px",
                                                border: "2px solid var(--border-color)",
                                                borderTopColor: "var(--accent-primary)",
                                                borderRadius: "50%",
                                                animation: "spin 1s linear infinite"
                                            }}></div>
                                            Processing...
                                        </div>
                                    ) : outputText || "Your results will appear here..."}
                                </div>
                            </div>
                        </div>

                        <div className="workspace-footer">
                            <span className="char-count">
                                {inputText.length} characters · {inputText.split(/\s+/).filter(Boolean).length} words
                            </span>
                            <div style={{ display: "flex", gap: "12px" }}>
                                <button
                                    className="btn btn-secondary"
                                    onClick={() => { setInputText(""); setOutputText(""); }}
                                    style={{ padding: "12px 24px" }}
                                >
                                    Clear
                                </button>
                                <button
                                    className="btn btn-primary"
                                    onClick={handleProcess}
                                    disabled={isProcessing || !inputText.trim()}
                                    style={{ padding: "12px 24px" }}
                                >
                                    {tool.buttonText}
                                    <ArrowIcon />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Features Grid */}
            <section style={{ padding: "80px 0" }}>
                <div className="container">
                    <div className="section-header" style={{ marginBottom: "60px" }}>
                        <span className="section-label">Features</span>
                        <h2>Everything You Need</h2>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "24px" }}>
                        {tool.features.map((feature, index) => (
                            <div
                                key={index}
                                style={{
                                    padding: "32px",
                                    background: "var(--card-bg)",
                                    border: "1px solid var(--card-border)",
                                    borderRadius: "16px",
                                    textAlign: "center"
                                }}
                            >
                                <div style={{
                                    width: "56px",
                                    height: "56px",
                                    borderRadius: "14px",
                                    background: "var(--bg-secondary)",
                                    display: "flex",
                                    alignItems: "center",
                                    justifyContent: "center",
                                    margin: "0 auto 16px",
                                    fontSize: "24px",
                                    color: "var(--accent-primary)"
                                }}>
                                    ✓
                                </div>
                                <p style={{ fontSize: "16px", fontWeight: 500, color: "var(--text-primary)" }}>{feature}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Other Tools */}
            <section style={{ padding: "80px 0", background: "var(--bg-secondary)" }}>
                <div className="container">
                    <div className="section-header" style={{ marginBottom: "60px" }}>
                        <span className="section-label">More Tools</span>
                        <h2>Explore Other Tools</h2>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "24px" }}>
                        {Object.entries(toolsData)
                            .filter(([key]) => key !== slug)
                            .slice(0, 3)
                            .map(([key, t]) => (
                                <Link
                                    href={`/tools/${key}`}
                                    key={key}
                                    className="tool-card"
                                >
                                    <div className="tool-icon">{toolIcons[key] && React.createElement(toolIcons[key])}</div>
                                    <h3>{t.name}</h3>
                                    <p>{t.description}</p>
                                    <span className="tool-link">
                                        Try Now
                                        <ArrowIcon />
                                    </span>
                                </Link>
                            ))}
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer className="footer">
                <div className="container">
                    <div className="footer-grid">
                        <div className="footer-brand">
                            <Link href="/" className="logo">
                                Kreative<span>Space</span>
                            </Link>
                            <p>Empowering writers with AI-powered tools to create exceptional content. Write better, faster, smarter.</p>
                            <div className="footer-social">
                                <a href="#" aria-label="Twitter">
                                    <svg viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                                    </svg>
                                </a>
                                <a href="#" aria-label="LinkedIn">
                                    <svg viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                                    </svg>
                                </a>
                                <a href="#" aria-label="GitHub">
                                    <svg viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" />
                                    </svg>
                                </a>
                                <a href="#" aria-label="Instagram">
                                    <svg viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z" />
                                    </svg>
                                </a>
                            </div>
                        </div>

                        <div className="footer-column">
                            <h5>Tools</h5>
                            <ul className="footer-links">
                                <li><Link href="/tools/ai-detector">AI Detector</Link></li>
                                <li><Link href="/tools/citation-creator">Citation Creator</Link></li>
                                <li><Link href="/tools/grammar-checker">Grammar Checker</Link></li>
                                <li><Link href="/tools/paraphraser">Paraphraser</Link></li>
                                <li><Link href="/tools/summarizer">Summarizer</Link></li>
                                <li><Link href="/tools/translator">Translator</Link></li>
                            </ul>
                        </div>

                        <div className="footer-column">
                            <h5>Company</h5>
                            <ul className="footer-links">
                                <li><Link href="/about">About Us</Link></li>
                                <li><Link href="/blog">Blog</Link></li>
                                <li><Link href="/careers">Careers</Link></li>
                                <li><Link href="/press">Press Kit</Link></li>
                                <li><Link href="/contact">Contact</Link></li>
                            </ul>
                        </div>

                        <div className="footer-column">
                            <h5>Resources</h5>
                            <ul className="footer-links">
                                <li><Link href="/help">Help Center</Link></li>
                                <li><Link href="/api">API Docs</Link></li>
                                <li><Link href="/integrations">Integrations</Link></li>
                                <li><Link href="/tutorials">Tutorials</Link></li>
                                <li><Link href="/changelog">Changelog</Link></li>
                            </ul>
                        </div>

                        <div className="footer-column">
                            <h5>Legal</h5>
                            <ul className="footer-links">
                                <li><Link href="/privacy">Privacy Policy</Link></li>
                                <li><Link href="/terms">Terms of Service</Link></li>
                                <li><Link href="/cookies">Cookie Policy</Link></li>
                                <li><Link href="/security">Security</Link></li>
                                <li><Link href="/gdpr">GDPR</Link></li>
                            </ul>
                        </div>
                    </div>

                    <div className="footer-huge-text">
                        <h2>KREATIVESPACE</h2>
                    </div>

                    <div className="footer-bottom">
                        <p>© 2025 KreativeSpace. All rights reserved.</p>
                        <div className="footer-bottom-links">
                            <Link href="/privacy">Privacy</Link>
                            <Link href="/terms">Terms</Link>
                            <Link href="/cookies">Cookies</Link>
                            <Link href="/sitemap">Sitemap</Link>
                        </div>
                    </div>
                </div>
            </footer>

            <style jsx>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
        </div>
    );
}
